# Message from GPVTG NMEA String
Header header

string message_id

# track made good relative to true north
float64 track_t
string track_t_ref

# track made good relative to magnatic north
float64 track_m
string track_m_ref

# measured horizontal speed in knots
float32 speed_n
string speed_n_unit

# measured horizontal speed in km/hr
float32 speed_k
string speed_k_unit

# mode indicator
string mode_indicator