# Message from GPVTG NMEA String
Header header

string message_id

# Track made good relative to true north
float32 track_t
string track_t_ref

# Track made good relative to magnetic north
float32 track_m
string track_m_ref

# Measured horizontal speed in knots
float32 speed_n
string speed_n_unit

# Measured horizontal speed in km/hr
float32 speed_k
string speed_k_unit

# Mode indicator
string mode_indicator
